[ADD] SetHouseWork, WriteHouseWork - 집안일 생성 API 연결
fairer-iOS/fairer-iOS pull request #119
Opened 2023-03-26 08:51 UTC by Guel-git

## 📣 Related Issue
- close #102 

## 👩‍💻 Contents & Screenshot
먼저 죄송합니다... 잘게 쪼개려고 했는데 또 커졌네요,,,, 허허

#### SetHouseWorkViewController 
<img src="https://user-images.githubusercontent.com/81340603/227764899-af2f93eb-fa58-45e6-b26f-b97e840c7b39.png" width=150px /> <img src="https://user-images.githubusercontent.com/81340603/227764901-930b0073-a396-4e32-8ecd-24c9f8359e07.png" width=150px /> <img src="https://user-images.githubusercontent.com/81340603/227764903-7b1c0b5e-84e2-4b23-a025-4147b40f4ec8.png" width=150px />|
<img width="400" alt="스크린샷 2023-03-26 오후 5 41 23" src="https://user-images.githubusercontent.com/81340603/227764889-8ea49d68-6801-461a-93e3-38ee5c9077fc.png">

#### WriteHouseWorkViewController
<img src="https://user-images.githubusercontent.com/81340603/227765060-ee9b9dae-f3c3-4928-a164-575c5ffa816d.png" width=200px /> <img width="400" alt="스크린샷 2023-03-26 오후 5 45 11" src="https://user-images.githubusercontent.com/81340603/227765077-32f63e48-78ec-4e75-8031-d7aca5e7e45b.png">

1. HouseWorkRequest & HouseWorkResponse 구현
2. HouseWorkAPI & HouseWorkRouter 구현
3. SetHouseWorkViewController 와 WriteHouseWorkViewController 에 각각 바인딩
4. ImageCacher 생성
5. mockData가 포함된 HouseWork 삭제

그외 진행사항들은 코멘트로 남길게요 ^^... 

## 📌 Review Point
102번 브랜치로 이동하셔서 root view를 SetHouseWorkViewController 와 WriteHouseWorkViewController 로 바꾸시고 테스트하시면 됩니다!
코드를 완전하게 이해하긴 시간이 많이 걸릴 것 같아서,,, 에러 케이스 위주로 제보해주시면 수정하도록 하겠습니다,,,죄송합니다...!

## 🔓 Next Step
- 집안일 수정 api 연결

## 📬 Reference
[split 대신 string 나누기]
https://0urtrees.tistory.com/95

2023-03-28 09:02 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/View/SetHouseWorkCollectionView.swift
> +    lazy var isSelectedDetailHouseWork = [totalHouseWorks[0].houseWorkName]
요기는 왜 lazy var 인가요?

2023-03-28 09:03 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Network/Foundation/ImageCacheManager.swift
> +class ImageCacheManager {
final 붙여도 되겠군요.

2023-03-28 09:58 UTC, hongjunehuke requested changes
코드리뷰 수정이랑 아래 충돌난것만 해결되면 될거 같아요!

2023-03-28 09:58 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/HouseWorksRequest.swift
> +    var scheduledTime: String = ""
p5;
var scheduledTime: String = "" 보다는
var scheduledTime: String = String() 또는 
var scheduledTime: String? 
으로 처리해두는게 더 정확한 의미인것 같은데 어떻게 생각하시나요??

2023-03-29 06:07 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/View/SetHouseWorkCollectionView.swift
> +    lazy var isSelectedDetailHouseWork = [totalHouseWorks[0].houseWorkName]
isSelectedDetailHouseWork에서 사용한 totalHouseWorks가 SetHouseWorkVC가 viewDidLoad할 때 넣어주는데 처음부터 초기화된 데이터가 아니라서 lazy 를 넣어야 하더라구요!

2023-03-29 06:26 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/ViewController/SetHouseWorkViewController.swift
> +            if self?.houseWorks.count == 0 {
[18152f1](https://github.com/fairer-iOS/fairer-iOS/pull/119/commits/18152f14457034c3c98f678885281d10ad1c93b7)
수정해서 반영해두었습니다! 감사해요 ㅎㅎ

2023-03-29 06:26 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/HouseWorksRequest.swift
> +    var scheduledTime: String = ""
[18152f1](https://github.com/fairer-iOS/fairer-iOS/pull/119/commits/18152f14457034c3c98f678885281d10ad1c93b7)
오이 좋습니다! 감사해요!

2023-03-29 06:26 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Network/Foundation/ImageCacheManager.swift
> +class ImageCacheManager {
[18152f1](https://github.com/fairer-iOS/fairer-iOS/pull/119/commits/18152f14457034c3c98f678885281d10ad1c93b7)
오 매의 눈 규철님,,,, final ... 명심하기... 감사합니당!

2023-03-29 07:32 UTC, hongjunehuke approved these changes
수고하셨습니다~~!!

2023-03-29 10:37 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/HouseWork/WriteHouseWork/WriteHouseWorkViewController.swift
> +        case .once:
[b03844d](https://github.com/fairer-iOS/fairer-iOS/pull/119/commits/b03844dba3f2b963e70aa9e92adb503a4c1e5911)
오이 ~ 나머지는 default 처리해뒀습니당 ! 감사합니당 ㅎㅎ

2023-03-29 10:44 UTC, kimkyuchul approved these changes
수고하셨습니다.

2023-03-29 10:49 UTC, merged