[ADD] members - 내 정보 조회 API 구현 및 그룹 메인 뷰에 바인딩
fairer-iOS/fairer-iOS pull request #136
Opened 2023-04-05 05:38 UTC by kimkyuchul

## 📣 Related Issue

- close #135

## 👩‍💻 Contents & Screenshot

![Simulator Screen Shot - iPhone 13 mini - 2023-04-05 at 14 33 57](https://user-images.githubusercontent.com/25146374/229989944-06c8a8ae-3f2c-4f89-bb75-6be0c4ce435d.png)

- member 정보 조회 API를 생성하고 그룹메인 뷰에 연결했습니다.

## 🧐 Question

didSet이나 DispatchQueue를 사용했을 때 서버 통신이 느린 점에 대한 질문
- 뷰가 만들어짐과 동시에 통신이 이루어져서 정보를 같이 가져 와야 하는데, 뷰가 만들어 진 후 서버 통신이 되어서 뭔가 통신 하는 부분이 한박자 느린 느낌이 듭니다. 공부가 필요하거나 이래서 비동기 프레임워크를 쓰나? 하는 생각이 듭니다. 다른 뷰도 마찬가지 일 거 같아요.

## 🔓 Next Step

- 멤버 API

2023-04-06 08:47 UTC, hongjunehuke requested changes

2023-04-06 08:47 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
> +        NetworkService.shared.members.getMemberInfo { [weak self] result in
p3;
@escaping 방식으로 바꾸고 데이터 처리는 따로 함수 만들어서 하는게 어떤가요?

2023-04-08 10:18 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
> +        label.text = "안녕하세요. 님!\n새로 하우스를 만들거나 참여해주세요."
p2;
제가 생각하기에 어색한 점은 
비어있는 userName이 통신이 완료됨에 따라 로딩되어 label text가 밀려난다는 건데요.
고민하시던 부분에 본질적인 해결이 될지 모르겠지만,
그냥 텍스트 자체를 userName이 들어왔을 때 넣어주는 게 덜 어색해보이는 것 같아요!
```suggestion
```
삭제해서 실행해보시면 느낌이 조금 다른 것을 확인하실 수 있습니다!
(그리고 textliteral로 넣어주시면 좋을 것 같아요!)

2023-04-08 10:19 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
> +    private var userName:String = String() {
p4;
```suggestion
    private var userName: String = String() {
```
띄어쓰기 부탁드립니다,,, ㅎㅎ

2023-04-09 03:03 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
> +    private var userName:String = String() {
[cc9e6af](https://github.com/fairer-iOS/fairer-iOS/pull/136/commits/cc9e6afeef76294d44564276b41b5b42b4c31c48)

2023-04-09 03:03 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
> +        label.text = "안녕하세요. 님!\n새로 하우스를 만들거나 참여해주세요."
[ac6260d](https://github.com/fairer-iOS/fairer-iOS/pull/136/commits/ac6260d49db8a7c03df4aabd08ab6c6c4c44fbdc)

2023-04-09 03:03 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
> +        NetworkService.shared.members.getMemberInfo { [weak self] result in
[ac6260d](https://github.com/fairer-iOS/fairer-iOS/pull/136/commits/ac6260d49db8a7c03df4aabd08ab6c6c4c44fbdc)

2023-04-09 04:16 UTC, hongjunehuke approved these changes

2023-04-09 04:16 UTC, merged