[ADD] WriteHouseWork - 집안일 수정 & 삭제
fairer-iOS/fairer-iOS pull request #141
Opened 2023-04-05 12:10 UTC by Guel-git

## 📣 Related Issue
- close #138 

## 👩‍💻 Contents & Screenshot
WriteHouseWork ViewController 에 data binding을 하기 전 api를 세팅하는 PR 입니다.
아직 디자인이 필요한 부분이 있어서 (수정/삭제시 뜨는 얼럿) 이후 작업에서 데이터 바인딩과 UI 작업 일부를 같이 할 예정입니다.

[DTO]
- EditHouseWorkRequest/Response 생성
- DeleteHouseWorkRequest 생성
[Router]
- HouseWorks Router: putEditHouseWork, deleteHouseWork 추가
[API]
- HouseWorks API: putEditHouseWork, deleteHouseWork api 메소드 생성
[WriteHouseWorkVC]
- api extension 메소드 추가
- 삭제 버튼 생성 및 세팅

## 🔓 Next Step
- WriteHouseWorkVC - 데이터 바인딩 및 UI 작업 일부

2023-04-06 01:21 UTC, kimkyuchul approved these changes
수고하셨습니다~

2023-04-06 08:42 UTC, hongjunehuke requested changes

2023-04-06 08:42 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/DeleteHouseWorkRequest.swift
> +    var deleteStandardDate: String
p5;
옵셔널 처리 해주는게 안전하다고 생각하는데 어떤가요?

2023-04-06 08:42 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/EditHouseWorkRequest.swift
> +    var assignees: [Int]
p5;
여기도요! 옵셔널 처리 어떤가요?

2023-04-06 08:42 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/EditHouseWorkResponse.swift
> +    var houseWorkId: Int
p5;
여기도요!

2023-04-08 14:06 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/EditHouseWorkRequest.swift
> +    var assignees: [Int]
앗 혹시 Request에서 필수인 변수에도 옵셔널을 사용하나요?? (진짜 몰라서.. 여쭤봅니다..ㅎㅎ)

2023-04-08 14:09 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/EditHouseWorkResponse.swift
> +    var houseWorkId: Int
[9a0b6d7](https://github.com/fairer-iOS/fairer-iOS/pull/141/commits/9a0b6d7b3d46cb955594d2d398c9433268f9290e)
감사합니당! ㅎㅎ

2023-04-09 02:40 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/EditHouseWorkRequest.swift
> +    var assignees: [Int]
아 필수적으로 들어오는 변수에는 굳이 필요는 없지만, 혹시 모르니 저는 하는 편입니다.

2023-04-09 02:40 UTC, hongjunehuke approved these changes

2023-04-09 03:39 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/DeleteHouseWorkRequest.swift
> +    var deleteStandardDate: String
[08e0342](https://github.com/fairer-iOS/fairer-iOS/pull/141/commits/08e0342530e8dcfd82247c214bd2bce79761d67e)
수정했습니당! 감사해용 ㅎㅎ

2023-04-09 03:40 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/EditHouseWorkRequest.swift
> +    var assignees: [Int]
[08e0342](https://github.com/fairer-iOS/fairer-iOS/pull/141/commits/08e0342530e8dcfd82247c214bd2bce79761d67e)
오이 ~ 수정해서 반영해두었습니당 !

2023-04-09 03:41 UTC, merged