[ADD] 홈뷰 상단 팀 멤버 리스트 중 본인 확인
fairer-iOS/fairer-iOS pull request #149
Opened 2023-04-09 08:17 UTC by hongjunehuke

## 📣 Related Issue

- close #147

## 👩‍💻 Contents & Screenshot

![Simulator Screen Recording - iPhone 14 - 2023-04-09 at 17 15 14](https://user-images.githubusercontent.com/83629193/230761968-27209500-227e-4303-adbd-94cf98007979.gif)

1. 본인 정보 조회 이후 팀 정보 조회하여 본인 아이콘이 상단 팀 리스트에서 가장 왼쪽에 오도록 구현
2. 기본 loading view -> self.view.isUserInteractionEnabled 로 대체
3. 홈뷰 처음 들어갔을 때 의미 없이 뜨던 파란 뱃지 버그 해결
4. 주간 캘린더 가로 스크롤 연속으로 했을 때 발생되던 인덱스 참조 버그 해결

## 📌 Review Point

- 홈뷰에서 데이터 바인딩 속도가 조금 느린 부분이 있는데 (파란 뱃지), 해당 부분은 좀 더 고민해보려해요!

## 🔓 Next Step

- 홈뷰는 팀원 이미지 로딩만 해결만 남았고 전체적으로 마무리 되었습니다.

2023-04-09 13:05 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/Home/View/WeekCalendarView/HomeWeekCalendarCollectionView.swift
> +                if let countWorkLeftWeekCalendar = countWorkLeftWeekCalendar {
Q;

수정 전과 달라진 점이 무엇이였나요 ?? 어떤게 문제 였는지 궁금해용

2023-04-09 13:09 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
> +                    DispatchQueue.main.async {
Q;

이 곳을 `DispatchQueue.main.async`로 감싸지 않았을 때 차이가 있었나요?

2023-04-09 15:03 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Home/Home/View/WeekCalendarView/HomeWeekCalendarCollectionView.swift
> +                if let countWorkLeftWeekCalendar = countWorkLeftWeekCalendar {
아 네! 홈뷰가 로드 된 직후에는 서버의 데이터와 관계없이 당일 셀의 상단에 내부 텍스트가 비어있는 상태로 파란 뱃지가 항상 보여졌습니다. 
#149 해당 pr에서 위에서 설명된 버그를 수정하였습니다.

2023-04-09 15:11 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
> +                    DispatchQueue.main.async {
self.calendarDailyTableView.reloadData() 되는 부분이랑 self.view.isUserInteractionEnabled = true 부분이 UI와 상관있다고 생각해서 global() 큐가 아닌 main 큐에서 실행되어야 한다고 생각했었어요!
어떻게 생각하시나요??

2023-04-10 05:37 UTC, kimkyuchul requested changes

2023-04-10 05:37 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
> +        self.getMyInfoFromServer { response in
p3;

[weak self] 붙여야 할 것 같아요

2023-04-10 05:37 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
>          self.getTeamInfoFromServer() { response in
p3;

여기도 위와 동일합니다.

2023-04-10 05:37 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
> +                    DispatchQueue.main.async {
맞는거같아요

2023-04-10 08:58 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
>          self.getTeamInfoFromServer() { response in
[e12b68e](https://github.com/fairer-iOS/fairer-iOS/pull/149/commits/e12b68e13aee3469954189e3393b1a71b24177c6)

2023-04-10 08:58 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
> +        self.getMyInfoFromServer { response in
[e12b68e](https://github.com/fairer-iOS/fairer-iOS/pull/149/commits/e12b68e13aee3469954189e3393b1a71b24177c6)

2023-04-10 09:00 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
>          self.getTeamInfoFromServer() { response in
api 호출부분에서 모두 escaping closure 사용하고 있어서 전체적으로 [weak self] 추가했습니다!

2023-04-10 09:14 UTC, kimkyuchul approved these changes

2023-04-10 09:34 UTC, merged