[ADD] setting - 초대하기 뷰 구현
fairer-iOS/fairer-iOS pull request #150
Opened 2023-04-09 13:45 UTC by kimkyuchul

## 📣 Related Issue

- close #148 

## 👩‍💻 Contents & Screenshot

![Simulator Screen Recording - iPhone 13 mini - 2023-04-09 at 22 31 03](https://user-images.githubusercontent.com/25146374/230776210-7879f6b8-3d02-41f5-b0bb-c85632b703f3.gif)

- 설정 > 초대하기 뷰를 구현

## 📌 Review Point

- TeamAPI 쪽 이슈가 있어서 준혁님의 "[ADD] 홈뷰 상단 팀 멤버 리스트 중 본인 확인 #149"가 머지가 된 후 테스트가 가능할 것 같습니다!..
- 그룹 > 초대하기 뷰와 거의 동일해서 크게 테스트 할 것은 없을 것 같습니다.

## 🔓 Next Step

-  애플 로그인

2023-04-09 15:15 UTC, hongjunehuke requested changes

2023-04-09 15:15 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Setting/SettingInviteCode/SettingInviteCodeViewController.swift
> +             guard let inviteCode = data.inviteCode else { return }
p5;
inviteCode & inviteCodeTimeString & inviteCodeTimeDate 중에 inviteCode 만 데이터가 들어오지 않고 나머지는 들어오는 경우가 발생했을 때, 첫 guard문에서 함수가 종료될 것 같은데 여러 값을 언랩핑 해야할 때 if let을 사용하는게 어떤가요?

2023-04-09 15:15 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Setting/SettingInviteCode/SettingInviteCodeViewController.swift
> +            guard let houseName = data.teamName else { return }
p5;
위에서 했던 리뷰와 같은 맥락입니다!

2023-04-10 05:02 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Setting/SettingInviteCode/SettingInviteCodeViewController.swift
> +             guard let inviteCode = data.inviteCode else { return }
[a293e76](https://github.com/fairer-iOS/fairer-iOS/pull/150/commits/a293e768c55fd4d9cdceecc9347811f33b3ed16c)

2023-04-10 05:02 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Setting/SettingInviteCode/SettingInviteCodeViewController.swift
> +            guard let houseName = data.teamName else { return }
[a293e76](https://github.com/fairer-iOS/fairer-iOS/pull/150/commits/a293e768c55fd4d9cdceecc9347811f33b3ed16c)

2023-04-10 05:04 UTC, kimkyuchul reviewed
온보딩 플로우에서의 InviteCodeView의 경우 건너뛰기 버튼이 존재하지만, 설정 > InviteCodeView의 경우 건너뛰기 버튼이 존재하지 않씁니다. 그래서 inviteCodeButtonView 내부에 버튼을 스택뷰로 한번 감싸고convenience init으로 skip 버튼의 isHidden을 처리해서 설정 > InviteCodeView에서는 skip버튼이 노출되지 않도록 설정했습니다.

2023-04-10 05:05 UTC, hongjunehuke approved these changes
수고하셨어요~!

2023-04-10 09:36 UTC, merged