Feature/154 connect view navigation
fairer-iOS/fairer-iOS pull request #156
Opened 2023-04-13 05:07 UTC by hongjunehuke

## 📣 Related Issue

- close #154 

## 👩‍💻 Contents & Screenshot

- 앱 전체적인 뷰 네비게이션 연결

2023-04-13 06:59 UTC, hongjunehuke commented
제가 집안일 추가하기 쪽 뷰들의 push 흐름을 잘못 알고 있어서 수정했습니다!
[4c68560](https://github.com/fairer-iOS/fairer-iOS/pull/156/commits/4c685601fb05b67d43a85fec138a7d0c0b7a8c58)

2023-04-13 07:18 UTC, hongjunehuke commented
연속된... commit... 죄송합니다... 마지막입니다.
[b95d87d](https://github.com/fairer-iOS/fairer-iOS/pull/156/commits/b95d87dd35aa16db6fa49e59c27eba14cb28a783)
navigation push 중복되던 버그, 디버깅한 commit 입니다.

2023-04-14 06:27 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Auth/OnboardingName/OnboardingNameViewController.swift
> +        setButtonAction()
q; 

요거는 왜 viewWillAppear 존재하나요?

2023-04-14 06:28 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Auth/OnboardingProfile/ViewController/OnboardingProfileViewController.swift
> +        setButtonAction()
Q;

위와 마찬가지입니다.

2023-04-14 06:28 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Group/EnterHouse/EnterHouseViewController.swift
> +        setButtonAction()
Q;

위와 마찬가지 입니다.

2023-04-14 06:30 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
> +        setButtonAction()
Q;

위와 마찬가지 입니다.

2023-04-14 06:31 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Group/HouseInfo/ViewController/HouseInfoViewController.swift
> +        setButtonAction()
Q;

위와 마찬가지 입니다.

아니면 setButtonAction()가 계속 호출되기 보단 baseViewController에 넣어둬도 좋을 거 같아요

2023-04-14 06:32 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Group/HouseMakeName/HouseMakeNameViewController.swift
> +extension HouseMakeNameViewController {
Q;

그런데 버튼 부분을 모두 extension으로 뺀 이유가 있을까요?

2023-04-14 07:00 UTC, kimkyuchul requested changes

2023-04-14 07:02 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Global/Extension/UIApplication+Extension.swift
> +    class func topViewController(base: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController? {
<img width="767" alt="스크린샷 2023-04-14 오후 4 01 13" src="https://user-images.githubusercontent.com/25146374/231968197-d82c4d7b-5526-45e2-a0d3-023770a7fc0f.png">

p2; 

keyWindow' 는 iOS13 부터  deprecated 된 듯 보입니다..

2023-04-14 09:20 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Auth/OnboardingName/OnboardingNameViewController.swift
> +        setButtonAction()
[b95d87d](https://github.com/fairer-iOS/fairer-iOS/pull/156/commits/b95d87dd35aa16db6fa49e59c27eba14cb28a783)

2023-04-14 09:20 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Auth/OnboardingProfile/ViewController/OnboardingProfileViewController.swift
> +        setButtonAction()
[b95d87d](https://github.com/fairer-iOS/fairer-iOS/pull/156/commits/b95d87dd35aa16db6fa49e59c27eba14cb28a783)

2023-04-14 09:20 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Group/EnterHouse/EnterHouseViewController.swift
> +        setButtonAction()
[b95d87d](https://github.com/fairer-iOS/fairer-iOS/pull/156/commits/b95d87dd35aa16db6fa49e59c27eba14cb28a783)

2023-04-14 09:20 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
> +        setButtonAction()
[b95d87d](https://github.com/fairer-iOS/fairer-iOS/pull/156/commits/b95d87dd35aa16db6fa49e59c27eba14cb28a783)

2023-04-14 09:20 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Group/HouseInfo/ViewController/HouseInfoViewController.swift
> +        setButtonAction()
[b95d87d](https://github.com/fairer-iOS/fairer-iOS/pull/156/commits/b95d87dd35aa16db6fa49e59c27eba14cb28a783)

2023-04-14 09:21 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Group/HouseInfo/ViewController/HouseInfoViewController.swift
> +        setButtonAction()
오! baseViewController에 넣는것도 좋을것 같네요 해당 부분은 리팩토링할 때 논의해봐요!

2023-04-14 09:39 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Group/HouseMakeName/HouseMakeNameViewController.swift
> +extension HouseMakeNameViewController {
버튼 연결 부분을 따로 정리해서 보기 편하기 위해 extension으로 뺐습니다.
그리고 해당 부분을 정적 디스패치 쪽으로 빼면 어떨까하여 extension으로 뺐습니다!

2023-04-14 09:41 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Global/Extension/UIApplication+Extension.swift
> +    class func topViewController(base: UIViewController? = UIApplication.shared.keyWindow?.rootViewController) -> UIViewController? {
맞습니다... 해당 부분에 대한 수정도 이후 디버깅 PR에서 진행하겠습니다!

2023-04-14 09:47 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.ios.fairer1;
[2ecf18a](https://github.com/fairer-iOS/fairer-iOS/pull/156/commits/2ecf18aa1a761785f608286db2cd657ee9501335)

2023-04-15 03:01 UTC, kimkyuchul approved these changes

2023-04-15 03:02 UTC, kimkyuchul commented
온보딩 -> 홈으로 이동할 때도 검정화면 이슈 있습니다 이후 버그 pr에서 수정 부탁드려요 ~

2023-04-15 05:13 UTC, hongjunehuke commented
넵! 확인했습니다! 오늘 중으로 해당 부분 수정된 PR 올릴게요!

2023-04-15 05:13 UTC, merged