[FEAT] 토큰 재갱신 구현
fairer-iOS/fairer-iOS pull request #170
Opened 2023-04-20 08:22 UTC by kimkyuchul

## 📣 Related Issue

- close #160 

## 👩‍💻 Contents & Screenshot

- Alamofire RequestInterceptor 활용해서 401(토큰만료)가 떴을 때 모든 API 호출 시점에 엑세스 토큰을 새로 반환하도록 하였습니다.
- UserDefaultHandler를 구현했습니다. @propertyWrapper를 활용해서 UserDefault get, set를 한번에 구현할 수 있도록 했습니다.
- RootHandler를 구현했습니다. 만약 엑세스토큰 리퀘스트가 실패하거나, 엑세스토큰이 존재하지 않는 유저가 존재 시 최상위 뷰를 login로 설정되도록 구현했습니다.
## 📌 Review Point

매우 긴 내용이여서 죄송합니다.

첫 번째로 저희 로그인 로직은 다음과 같습니다.
1. 구글 or 애플에서 들어오는 토큰을 헤더에 저장한다.
2. 해당 헤더로 postLogin API를 호출한다.
3. postLogin API는 해더에 넣어 보낸 소셜 토큰을 서버 엑세스 토큰과 서버 리프레쉬 토큰으로 반환해줍니다.
4. 해당 엑세스 토큰과 리프레쉬 토큰을 UserDefault에 저장합니다. (헤더도 설정됨)

다음은 토큰 401 로직 입니다.
1. 헤더의 엑세스 토큰이 15분 이후 엑세스 만료 됩니다.
2. Interceptor는 401을 확인합니다.
3. 헤더 엑세스를 리프레쉬 엑세스로 교체 해줍니다. ( 여기가 문제 입니다.) 
4. 리프레쉬 토큰이 설정된 헤더로 getToken API를 호출해 새로운 엑세스 토큰으로 변경합니다.

Interceptor는 쉽게 얘기해서 서버에 요청을 보내기 전에, 중간에 가로채서 어떤 작업을 한 뒤 다시 서버로 보내는 역할을 합니다.
즉, 모든 API가 호출될 때마다 중간 중간 계속 401 만료를 체크하고 getToken API를 호출하는 겁니다.

## 🧐 Question

이틀을 잡고 있는데 풀리지 않는 문제가 있습니다.

Interceptor 쪽 코드를 보면 중간에 보면 엑세스 토큰을 리프레쉬 토큰으로 변경해주는 `UserDefaultHandler.shared.acceesToken = UserDefaultHandler.shared.refershToken`가 존재합니다. 위에서 설명한 토큰 401 로직 중 3번에 해당합니다.

이 코드가 이후에 존재하는 getToken이 호출되기 전에 설정이 되지 않습니다. getToken이 불린 후 엑세스 토큰을 리프레쉬 토큰으로 변경되니 **401 이 뜬 후 (만료된 후) api 첫 호출하면 400이 뜨고 두번째 호출부터 토큰이 정상적으로 교체됩니다. ( 위의 영상 참고)**

**시도해본 방법**
<img width="808" alt="스크린샷 2023-04-20 오후 4 35 59" src="https://user-images.githubusercontent.com/25146374/233302883-e40ba77b-b196-4c33-ad49-bbbb1fd0b742.png">
- getToken API의 헤더를 리프레쉬 토큰으로 설정한 뒤 진행해 보았습니다. -> 이러면 자동으로 헤더가 리프레쉬 토큰으로 설정되니 문제가 없다고 판단했습니다.
<img width="806" alt="스크린샷 2023-04-20 오후 5 13 39" src="https://user-images.githubusercontent.com/25146374/233303221-744840ca-a76c-427e-90d5-5ec6347a38e9.png">
- 하지만 adapt 쪽에서 헤더가 acceesToken으로 설정이 되어 있어서 **현재 헤더: 리프레쉬 토큰, adapt 헤더: 기존 엑세스 토큰** 이렇게 서로 맞지 않아 400이 발생했습니다.

테스트 방법
- 구글 로그인 설정( 카톡방 공지)를 제외하곤 모든 설정이 완료되어있습니다.
- 구글 로그인 설정 후 구글 로그인 -> 온보딩 뷰 -> 그룹 로그인으로 넘어갈 때 API가 호출되는데 5분 이후 호출하시면 됩니다.

## 🔓 Next Step

- 이슈 해결 및 스플래쉬 뷰에서 자동 로그인 구현

## 📬 Reference

https://ios-development.tistory.com/730?category=899471
https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#adapting-and-retrying-requests-with-requestinterceptor

2023-04-22 07:17 UTC, hongjunehuke requested changes
서버 쪽 리프레시 토큰 문제 해결되고 수정한뒤 PR 한번 더 올려주세요~

2023-04-22 07:17 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Global/Util/RootHandler.swift
> +        // 로그인 뷰로 이동
p1;
MARK 주석으로 수정해주세요~

2023-04-22 07:17 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Network/API/OauthAPI.swift
> +        authProvider.request(.getToken(clientType: "IOS", socialType: socialType)) { result in
p2;
TextLiteral에 따로 빼두면 좋을것 같아요

2023-04-30 03:26 UTC, hongjunehuke reviewed
일단 Request changes 열어둘게요!

2023-04-30 03:27 UTC, hongjunehuke approved these changes
일단 Request changes -> Approve 해둘게요

2023-05-04 09:25 UTC, kimkyuchul commented
인터셉터에서는 401 시 리프레쉬 토큰으로 헤더만 변경해주고, api에서 200 시 리스폰스 헤더로 들어오는 엑세스 토큰을 헤더로 설정되도록 로직을 변경했습니다.

2023-05-16 12:31 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Global/Util/RootHandler.swift
> +        let LoginViewController = OnboardingNameViewController()
p2;
```suggestion
        let loginViewController = OnboardingNameViewController()
```
사소한 거지만,,, 소문자로 시작하는 건 어떤가요?

2023-05-16 13:23 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Network/API/MembersAPI.swift
> +                print("현재 적용 헤더 \(UserDefaultHandler.accessToken)")
p2;
이것도.. 나중에 삭제 부탁드립니다 ㅎㅎ..

2023-05-16 13:24 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Network/API/TeamsAPI.swift
> +                print("현재 적용 헤더 \(UserDefaultHandler.accessToken)")
p3;
이것도 부탁드려요 ㅎㅎ!

2023-05-16 13:49 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Auth/Login/Model/socialType.swift
> +//  socialType.swift
p2;
이것도 별로 아니지만,,, SocialType 으로 파일명 수정 부탁드려도 될까요..? ㅎㅎ

2023-05-16 14:35 UTC, Guel-git approved these changes
완전 고생 하셨습니당 ~~~~ 고민의 흔적이 보이는 pr 이네요,,,

2023-05-16 22:20 UTC, hongjunehuke approved these changes
너무 고생많으셨어요~

2023-05-16 22:20 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Global/Util/UserDefaultHandler.swift
> +    static var accessToken: String
p5;
static으로 선언되는 이유가 있을까요?
shared도 static으로 되어있어서 shared.accessToken으로 접근되지 않을까 해서요.

2023-05-16 22:20 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
> +                UserDefaultHandler.accessToken = idToken
p5;
shared.acceesToken -> accessToken로 수정된 이유를 알 수 있을까요?

2023-05-18 01:59 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Network/API/HouseWorksAPI.swift
> +                print("현재 적용 헤더 \(UserDefaultHandler.accessToken)")
주석 말씀하시는거죠? 주석 외 코드들은 디코딩에서 200 시 토큰 교체하도록 일단 다 넣어뒀어요

2023-05-18 02:15 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Global/Util/UserDefaultHandler.swift
> +    static var accessToken: String
UserDefaultHandler가 struct여서요 ~

싱글톤 패턴은 인스턴스를 전역적으로 접근 가능한 단일 객체로 만들기 위해 사용하는데, 구조체는 일반적으로 단순한 데이터 구조를 표현하는 데 사용되고 인스턴스를 공유하거나 전역 상태를 관리하는 데 적합하지 않다고 느껴서요 (struct에 싱글톤이 존재하는 코드 본 적 없는 거 처럼..)

2023-05-18 02:15 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
> +                UserDefaultHandler.accessToken = idToken
위와 동일함니다.

2023-05-18 02:27 UTC, merged