[ADD] 집안일 설정 완성
fairer-iOS/fairer-iOS pull request #71
Opened 2023-01-30 17:54 UTC by Guel-git

## 📣 Related Issue
- close #70 

## 👩‍💻 Contents & Screenshot
https://user-images.githubusercontent.com/81340603/215549193-9dcceaf0-e983-4cfe-b0c6-e6828c4a63a2.mp4

- 시간 설정 & 반복하기 Label 과 Switch 생성
- 시간 설정
   - DatePicker 생성
- 반복하기
   - 반복 주기 설정 (`RepeatCycleView` & `RepeatCycleMenu`)
   - 반복 요일 설정(`RepeatCycleCollectionView`)
   - 반복 정보 라벨(`RepeatCycleDayLabel`) 생성
- HouseWork Model 생성 및 Mockdata 연결
- 집안일 수정/삭제에 따른 Mockdata 수정/삭제
- 집안일 포커스 변경에 따른 담당자/시간설정/반복하기 업데이트 로직 구현
- 집안일 설정 화면과 관련된 화면 코드 정리

## 📌 Review Point
먼저 죄송합니다,,, 사이즈가 너무 큰 피알을 올려버렸네요,,, 나름 크기 줄인다고 3번에 나눠서 구현했는데도
이번 PR에서 UI 외에도 구현해야 할 로직이 너무 많았어요 ㅠㅠㅠ 한 번 시작하니 중간에 멈추면 다시 할 자신도 없어서 일단 다 해버렸습니다,,

1. HouseWork 모델 생성
   상단에 있는 집안일 CollectionView에서 어떤 Cell을 터치(포커스)하냐에 따라서 아래 있는 담당자 & 시간 & 반복 컴포넌트가 달라져야 하는 로직을 구현하기 위해 임의로 모델을 만들었습니다. Swagger 를 참고해서 제작했지만 타입이나 변수 이름이 완벽하게 일치하지 않습니다. UI 구현 단계에서 가장 적합한 형식으로 만들어 두었습니다. api 연결할 때 수정이 필요할듯 해요.
3. 준혁님께서 만들어 주신 addSubViews로 컴포넌트 올려봤습니다! 그래서 이전 PR(담당자)에서 개발한 부분이 일부 수정되었어요!
4. 반복주기를 enum으로 선언해두었습니다. `RepeatType`
   enum 안에는 week(매주), month(매달) type 이 존재합니다.
5. 담당자 부분부터 Scroll 가능하도록 ScrollView에 올려두었습니다. 시간 설정과 반복하기 토글이 모두 켜졌을 때만 Scroll 될거에요!
6. 이번에는 반복되는 코드가 많아서 VC 내 private 메소드를 많이 만들어봤습니다. 어떤 일을 하는 메소드인지를 다른 사람이 봐도 이해될 수 있도록 하고 싶었는데 메소드가 너무 많아서 오히려 어지러워진 게 아닌지 걱정이네요.. 준혁님께서 읽어보시고 의견 남겨주시면 감사하겠습니다..!

이외 설명이 필요한 부분은 코드에 직접 코멘트 남길게요! 

## 🔓 Next Step
- 집안일 직접 입력 뷰

## 📬 Reference
[배열을 문자열로 조인하기]
https://dmsitter.tistory.com/136

[CollectionView에서 Cell 사이 간격 지정하기]
https://88yhtserof.tistory.com/50

2023-01-30 17:57 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +    private var selectedHouseWorkIndex: Int = 0
선택된(포커싱된) 집안일 index를 저장하는 변수입니다!

2023-01-30 18:01 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +        didSelectDaysOfWeek()
1. didTappedHouseWork - SetHouseWorkCollectionView에서 집안일이 선택됐다면
2. didDeleteHouseWork - SetHouseWorkCollectionView에서 집안일이 삭제됐다면
3. didTappedRepeatCycleMenuButton - RepeatCycleMenu에서 매주/매달이 선택됐다면
4. didSelectDaysOfWeek - RepeatCycleCollectionView에서 반복 요일이 선택됐다면

2023-01-30 18:04 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +            $0.bottom.equalTo(0)
처음 화면에서 scrollView 위에 있는 contentView(UIView)의 크기를 명시적으로 하기 위해 bottom을 지정해줬습니다. 
이걸 지정해줘야 UISwitch가 작동합니다!

2023-01-30 18:08 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +    private func isTimeSelected(_ houseWork: Int) {
시간 설정을 했는지 확인하는 메소드 입니다.
1번 집안일의 시간을 설정한 후 2번 집안일로 넘어간 후 다시 1번 집안일을 수정하기 위해 1번 집안일을 터치했을 때 
(1)시간 설정 토글이 켜져있어야 하며, (2) timepicker가 보여야 합니다.

2023-01-30 18:09 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +    private func isRepeatSelected(_ houseWork: Int) {
반복하기를 설정했는지 확인하는 메소드입니다.
논리는 `isTimeSelected` 메소드와 동일합니다!

2023-01-30 18:10 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +    private func updateManagerTimeRepeat(_ houseWork: Int) {
상단에 집안일 cell 누를 때마다 해당 집안일에 맞는 담당자 & 시간 설정 & 반복하기를 불러오기 위한 메소드입니다!

2023-02-09 07:27 UTC, hongjunehuke requested changes

2023-02-09 07:27 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +        } else {
p1;
<img width="324" alt="스크린샷 2023-02-09 오후 4 10 29" src="https://user-images.githubusercontent.com/83629193/217742535-7ec8afe5-a47e-4f4d-88db-5302ef0387e1.png"><img width="320" alt="스크린샷 2023-02-09 오후 4 10 36" src="https://user-images.githubusercontent.com/83629193/217742562-18f74ade-25b9-4f77-81f5-9a1a50495d81.png">
반복하기 토클이 off 될 때, 반복 주기 박스가 함께 닫치지 않는것 같아요

2023-02-09 07:27 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +        case .week:
p5;
<img width="325" alt="스크린샷 2023-02-09 오후 4 17 27" src="https://user-images.githubusercontent.com/83629193/217743828-c9c8e85f-94ab-404a-8140-d10ec42cf57d.png">
피그마 상으로는 확인되진 않는데, 요일 선택되는 순서보다는 (월화수목금토일) 처럼 요일 순으로 정렬되는게 더 읽기 편해보이는것 같아요.

2023-02-09 07:27 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +            updateRepeatCycleDayLabel(.month, Date().singleDayToKoreanString)
p1;
<img width="337" alt="스크린샷 2023-02-09 오후 4 26 07" src="https://user-images.githubusercontent.com/83629193/217745394-3dd25c64-da63-4dd4-ac04-3861f22e7442.png">
우측 상단 datepicker로 날짜(월)를 변경하고, 반복주기를 '매달'로 설정했을 때 하단 텍스트에 설정한 날짜(월)로 텍스트가 나오지 않아요

2023-02-10 14:58 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +            updateRepeatCycleDayLabel(.month, Date().singleDayToKoreanString)
이 부분은 ,, 고민인 게 PHPicker 로 변경될 예정이라서 따로 로직을 넣어두진 않았습니다,,,!
(준혁님께서 개발해주시면,,, 슬쩍 가져오는 걸로,,,, 슬쩍 부탁드렸습니다,,,)

2023-02-10 15:01 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +        } else {
[6290a1e](https://github.com/fairer-iOS/fairer-iOS/pull/71/commits/6290a1e3754db9619e471d239c86b321db1e0784)
오 매의 눈이네요 👁👁 ㅋㅋㅋ 감사합니다!

2023-02-10 15:02 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +        case .week:
[6290a1e](https://github.com/fairer-iOS/fairer-iOS/pull/71/commits/6290a1e3754db9619e471d239c86b321db1e0784)
개발 할 때도 고민이 많이 된 부분이었는데, 말씀해주신 거 읽어보고 다시 생각해보니 요일 순으로 정렬되는 게 맞겠더라구요!
하지만 String List 로 구성된 요일을 입맛대로 정렬하는 방법이 떠오르지 않아서 고민을 하다가,,, .. 꼼수를 좀 썼습니다...
이 방법이 적절하지 않다고 생각하시면,,, 말씀 부탁드려요,,, ㅎㅎ

2023-02-11 07:48 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +        case .week:
오! 추가되는 코드가 많이 없는 방법같은데요!

2023-02-11 07:59 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +            updateRepeatCycleDayLabel(.month, Date().singleDayToKoreanString)
1c3846f6601789f7f0d78709c432f3fd8c46df70
해당 commit이 datepicker에서 datepicker 종료되는 시점에 클로저 형태로 넘겼습니다!

2023-02-11 08:00 UTC, hongjunehuke approved these changes
수고하셨어요!

2023-02-12 10:53 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
> +            updateRepeatCycleDayLabel(.month, Date().singleDayToKoreanString)
SetHouseWork 말고도 SelectHouseWork 의 calendar 도 수정해야 해서 일단 다 머지하고 수정하는 피알 따로 올릴게요!

2023-02-12 10:53 UTC, merged