Feature/75 set house rules
fairer-iOS/fairer-iOS pull request #78
Opened 2023-02-09 06:50 UTC by kimkyuchul

## 📣 Related Issue

- close #75 

## 👩‍💻 Contents & Screenshot

<img src="https://user-images.githubusercontent.com/25146374/217734939-742ac67f-864b-44c0-8d1d-487761243f8a.png" width="200" height="400"/>
- TextField 값 입력 후 엔터 선택 시 규칙 추가
- 규칙 테이블 뷰에서 x 선택 시 규칙 삭제
- TextField 16자 넘어가면 TextField에 경고 문구 생성

## 📌 Review Point

feature/75-set-house-rules 브랜치로 이동하셔서 root view를 SettingHomeRuleViewController로 바꿔주세요.

1. 테이블뷰로 규칙이 보여주는 뷰를 구성했는데, 테이블뷰의 height 값 설정의 경우 CGFloat로 설정이 됩니다. 그런데 피그마에서는 셀 높이가 48px로 설정되어 있어서 셀 크기를 맞추지 못하는 문제가 있었습니다. 더불어 테이블뷰의 X 버튼의 경우 버튼 height가 58인데 셀 크기는 48이라서 버튼 크기가 잘리는 문제가 발생했습니다.

## 🔓 Next Step

- 테이블뷰를 콜렉션뷰로 리펙토링?

2023-02-09 07:17 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        label.textColor = .black
p1;
```swift
        label.textColor = .gray800
```

textColor 수정 부탁드립니다!

2023-02-09 07:39 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        textField.layer.borderColor = UIColor.gray200.cgColor
p1;
피그마 보니까 유저가 텍스트 필드를 터치했을 때 (키보드가 올라와 있을 때) 포커싱 하는 의미에서 TextField에 회색 border가 들어가는 것으로 보여요!

keyboard가 올라오고 내려오는 것을 감시하는 observer를 가지고 있는 NotifictationCenter를 만들어 viewDidLoad에 올려두고,
keyboard가 올라올 때 border를 1로 border 색을 gray로 해주고, keyboard를 내릴 때 border를 0으로 바꿔주는 로직을 추가하면 좋을 것 같아요! 또 텍스트 최대 개수를 check하는 checkMaxLength에서 16이 넘어갔을 때 border color 만 negative20으로 바꿔주면 되겠죠?

```swift
    // MARK: - life cycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupDelegation()
        setupNotificationCenter() < 추가
    }

    private func setupNotificationCenter() {
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow), name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide), name: UIResponder.keyboardWillHideNotification, object: nil)
    }

    private func checkMaxLength() {
        let maxLength = 16
        if let text = settingHomeRuleTextField.text {
            if text.count > maxLength {
                settingHomeRuleTextField.layer.borderColor = UIColor.negative20.cgColor < border 색만 바꾸기
                HomeRuleTextFieldeWarningLabel.isHidden = false
            } else {
                HomeRuleTextFieldeWarningLabel.isHidden = true < 여기 있던 border width 코드 삭제
            }
        }
    }

    // MARK: - selector

    @objc private func keyboardWillShow(notification: NSNotification) {
        settingHomeRuleTextField.layer.borderWidth = 1
        settingHomeRuleTextField.layer.borderColor = UIColor.gray200.cgColor
    }
    
    @objc private func keyboardWillHide(notification:NSNotification) {
        settingHomeRuleTextField.layer.borderWidth = 0
    }
```

2023-02-09 07:49 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        label.setTextWithLineHeight(text: "텍스트는 16글자를 초과하여 입력하실 수 없어요.", lineHeight: 22)
이 부분은 제가 올린 [#73](https://github.com/fairer-iOS/fairer-iOS/pull/73) 머지되면 // MARK: - common 으로 textLiteral 빼주시면 감사하겠습니다!

2023-02-09 07:50 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    private lazy var HomeRuleTextFieldStackView: UIStackView = {
이 부분을 StackView로 묶으신 이유가 궁금합니다! ^__^

2023-02-09 08:07 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    }()
p2;
여기는 제가 만들어 둔 InfoLabelView라는 컴포넌트 사용하시면 될 것 같아요!

```swift
    private let settingHomeRuleInfoLabel: InfoLabelView = {
        let label = InfoLabelView()
        label.text = TextLiteral.settingHomeRuleInfoLabel
        label.textColor = .gray600
        label.imageColor = .gray200
        return label
    }()

    // MARK: - life cycle
   
    override func render() {
        view.addSubviews(settingHomeRulePrimaryLabel, settingHomeRuleTextFieldLabel, HomeRuleTextFieldStackView, settingHomeRuleInfoLabel, titleLabel, homeRuleTableView)
    
        settingHomeRuleInfoLabel.snp.makeConstraints {
            $0.top.equalTo(HomeRuleTextFieldStackView.snp.bottom).offset(SizeLiteral.componentPadding)
            $0.leading.equalToSuperview().inset(SizeLiteral.leadingTrailingPadding)
            $0.height.equalTo(22) < height 를 필수로 넣어주셔야 밑에 있는 컴포넌트들이 잘 자리잡습니다!
        }

        titleLabel.snp.makeConstraints {
            $0.top.equalTo(settingHomeRuleInfoLabel.snp.bottom).offset(24) < 기준 바꿔주기!
            $0.leading.equalToSuperview().inset(SizeLiteral.leadingTrailingPadding)
        }
```

2023-02-09 08:08 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    private let HomeRuleTextFieldeWarningLabel: UILabel = {
p1;
```swift
    private let homeRuleTextFieldWarningLabel: UILabel = {
```

code convention을 맞추기 위해 property 는 소문자로 시작해주세요! ^_^

2023-02-09 08:10 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    }()
p1;
```swift
    private let titleLabel: UILabel = {
        let label = UILabel()
        label.text = "규칙" < TextLiteral 로 부탁드립니다!
        label.textColor = .gray600
        label.font = .title1
        return label
    }()
```
font와 textColor 위처럼 수정 부탁드립니다!
text는 TextLiteral로 빼주시면 감사하겠습니당 ㅎㅎ

2023-02-09 08:13 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    private lazy var HomeRuleTextFieldStackView: UIStackView = {
스택뷰는 내부 뷰의 크기에 따라 사이즈(width, height)가 자동으로 정해져서 처음에는 경고문구 isHidden을 true로 설정해두었다가 16자가 넘으면 isHidden을 false로 변경해서 자동으로 스택뷰 사이즈가 커지도록 설정했습니다.

2023-02-09 08:15 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    }
p3;
이 부분은 BaseViewController에 이미 작성된 내용이라서 이 메소드 삭제하셔도 될 것 같아요!!

2023-02-09 08:17 UTC, hongjunehuke commented
p2;
<img width="345" alt="스크린샷 2023-02-09 오후 5 16 43" src="https://user-images.githubusercontent.com/83629193/217755348-858a8523-85c9-42c5-89b3-5730c468859a.png">
규칙에 해당하는 셀 높이가 피그마에 비해 큰것 같습니다.

2023-02-09 08:18 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        textField.layer.borderColor = UIColor.gray200.cgColor
아 근데 16자 이상 작성하고 키보드 내린 후에 다시 키보드가 올라오면 자동으로 빨간 border가 생겨야 하는데,,, 이 부분이 구현 안되네요,,, 호호 조금 더 고민해서 코드 추가할게요!

2023-02-09 08:20 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +            $0.top.equalTo(settingHomeRulePrimaryLabel.snp.bottom).offset(SizeLiteral.topPadding)
p1;
```swift
            $0.top.equalTo(settingHomeRulePrimaryLabel.snp.bottom).offset(40)
```
여기 offset이 SizeLiteral.topPadding(28)보다 큰 40입니다! 수정 부탁드려용 ㅎㅎ

2023-02-09 08:22 UTC, hongjunehuke requested changes

2023-02-09 08:22 UTC, hongjunehuke commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        textField.layer.borderColor = UIColor.gray200.cgColor
p1;
<img width="331" alt="스크린샷 2023-02-09 오후 5 05 36" src="https://user-images.githubusercontent.com/83629193/217753044-ef1d01f5-810e-44ef-86db-fefd13a83464.png">
뷰가 처음 뜨면 위 사진의 텍스트 필드 볼더가 있는것 같은데, 피그마에서는 아래 사진 처럼 디폴트가 볼더 없는 거더라고요.
<img width="402" alt="스크린샷 2023-02-09 오후 5 07 09" src="https://user-images.githubusercontent.com/83629193/217753368-27066820-ae8a-4a86-84a5-32c6878ff179.png">

2023-02-09 08:29 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        }
p1;
```swift
        if let text = settingHomeRuleTextField.text {
            if !text.isEmpty {
                dummyList.append(text)
                
                DispatchQueue.main.async {
                    self.homeRuleTableView.reloadData()
                }
                
                settingHomeRuleTextField.text =  ""
                settingHomeRuleTextField.resignFirstResponder()
            }
        }
```
빈 String도 추가되는 것 같아요!
빈 String 찾는 로직 추가해주시면 좋을 것 같아요! ㅎㅎ

2023-02-09 11:31 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        textField.layer.borderColor = UIColor.gray200.cgColor
```swift
// MARK: - func

private func checkMaxLength() {
            let maxLength = 16
            if let text = settingHomeRuleTextField.text {
                if text.count > maxLength {
                    settingHomeRuleTextField.layer.borderColor = UIColor.negative20.cgColor
                    settingHomeRuleTextField.layer.borderWidth = 1
                    settingHomeRuleTextFieldeWarningLabel.isHidden = false
                } else {
                    settingHomeRuleTextField.layer.borderColor = UIColor.gray200.cgColor
                    settingHomeRuleTextField.layer.borderWidth = 1
                    settingHomeRuleTextFieldeWarningLabel.isHidden = true
                }
            }
        }

// MARK: - extension

func textFieldDidChangeSelection(_ textField: UITextField) {
        checkMaxLength()
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
           if !isEditing {
               isEditing = true
               checkMaxLength()
           }
       }

    func textFieldDidEndEditing(_ textField: UITextField) {
           if isEditing {
               isEditing = false
               settingHomeRuleTextField.layer.borderWidth = 0
           }
       }
```
이렇게 isEditing 활용하면 유나님께서 위에 말씀하신 문제는 해결됩니다. 그런데 코드가 조금 뭔가 가독성이 안좋아 보이긴합니다..

2023-02-09 11:39 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        }
16글자 초과 찾는 로직도 추가했습니다.

2023-02-09 11:48 UTC, kimkyuchul commented
규칙에 해당하는 셀 높이가 피그마에 비해 크게 잡혀야 UI가 깨지지 않는 문제를 대충 해결은 하였습니다.

1.  X 버튼의 이미지 크기가 58px이라서 x 버튼의 height, width 값을 58px로 설정했습니다.
2. 더불어 셀의 크기도 피그마에는 48px로 설정되어 있으나, 버튼과 같은 크기인 58로 rowHeight를 설정 해주었습니다.
<img width="368" alt="스크린샷 2023-02-09 오후 6 11 59" src="https://user-images.githubusercontent.com/25146374/217803560-c2403227-9bdb-4a78-9937-f022d373969b.png">

3. 하지만 여전히 버튼의 크기가 잘리는 것을 확인 했고 셀에 inset을 주고 있다는 것을 확인했습니다.
4. 그래서 최종적으로 셀의 rowHeight를 74(58px + 16px(inset값))로 변경하니 셀이 얼추 피그마와 비슷하게 설정되었습니다.
<img width="642" alt="스크린샷 2023-02-09 오후 8 44 15" src="https://user-images.githubusercontent.com/25146374/217803808-54183f5b-3775-4745-a330-19882c0e44e4.png">

2023-02-09 12:05 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        }
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-09 12:05 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +            $0.top.equalTo(settingHomeRulePrimaryLabel.snp.bottom).offset(SizeLiteral.topPadding)
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-09 12:05 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    }
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-09 12:06 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    }()
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-09 12:06 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    private let HomeRuleTextFieldeWarningLabel: UILabel = {
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-09 12:06 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    }()
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-09 12:06 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +    private lazy var HomeRuleTextFieldStackView: UIStackView = {
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-09 12:06 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        textField.layer.borderColor = UIColor.gray200.cgColor
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-09 12:06 UTC, kimkyuchul commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleViewController.swift
> +        label.textColor = .black
[0ebce2f](https://github.com/fairer-iOS/fairer-iOS/pull/78/commits/0ebce2f818e45bc61642876975e8648a8772a248)

2023-02-13 12:24 UTC, Guel-git commented
여기 브랜치가 조금 이상한 것 같은데 무슨 일 있었나용 ???

2023-02-13 15:33 UTC, kimkyuchul commented
rebase를 한번 진행했었습니다. 그 이후에 푸쉬하는 과정에서 커밋이 들어가게 된 거 같아요..

2023-02-15 06:41 UTC, hongjunehuke approved these changes

2023-02-15 06:52 UTC, Guel-git commented on fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/SettingHomeRuleTableViewCell.swift
> +class SettingHomeRuleTableViewCell: BaseTableViewCell {
p2;
```swift
final class SettingHomeRuleTableViewCell: BaseTableViewCell {
```
final 부탁드립니다!

2023-02-15 07:44 UTC, merged